import Link from "next/link";
import { Activity, BarChart3, BrainCircuit, CheckCircle2, CircleDollarSign, ClipboardList, Cpu, FileText, Gauge, HeartPulse, PackageSearch, ShieldCheck, Smartphone, UserCog, Users, Wrench } from "lucide-react";
import { AdminSidebar, AuditOperations, BookingOperations, OperationsCharts, ReportOperations, type AuditOperation, type BookingOperation, type ChartPoint, type HeatPoint, type ReportOperation } from "@/components/admin-console";
import { Logo } from "@/components/ui";
import { requireSession } from "@/lib/auth";
import { getServerEnv } from "@/lib/env";
import { prisma } from "@/lib/prisma";
import { parseAdminModule, type AdminModule } from "@/lib/admin-modules";

type Bookings = Awaited<ReturnType<typeof prisma.booking.findMany>>;
type Diagnoses = Awaited<ReturnType<typeof prisma.diagnosis.findMany>>;

export default async function AdminConsole({ searchParams }: { searchParams: Promise<{ module?: string }> }) {
  const session = await requireSession("admin", "/admin/login");
  const requested = (await searchParams).module;
  const activeModule = parseAdminModule(requested);
  const env = getServerEnv();
  const dataModules: AdminModule[] = ["overview", "ai", "bookings", "customers", "technicians", "reports", "inventory", "logs", "notifications"];
  let bookings: Bookings = [];
  let diagnoses: Diagnoses = [];
  let unavailable = false;
  if (dataModules.includes(activeModule)) {
    try {
      [bookings, diagnoses] = await Promise.all([
        prisma.booking.findMany({ orderBy: { createdAt: "desc" }, take: 250 }),
        prisma.diagnosis.findMany({ orderBy: { createdAt: "desc" }, take: 500 }),
      ]);
    } catch { unavailable = true; }
  }

  const context = buildContext(bookings, diagnoses);
  return <div className="min-h-screen bg-slate-100 text-slate-950 dark:bg-slate-950 dark:text-slate-100 xl:flex">
    <AdminSidebar email={session.email} activeModule={activeModule}/>
    <div className="min-w-0 flex-1">
      <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/90 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/90">
        <div className="flex min-h-16 items-center justify-between gap-4 px-4 sm:px-7"><div className="xl:hidden"><Logo/></div><div className="hidden xl:block"><b>FixMind Operations</b><small className="ml-3 text-slate-500">{moduleTitle(activeModule)}</small></div><div className="flex items-center gap-2"><span className={`badge ${unavailable ? "badge-amber" : "badge-green"}`}><HeartPulse size={14}/>{unavailable ? "Database degraded" : "All systems operational"}</span><Link href="/" className="btn btn-secondary !h-10 !px-3 text-xs">Public site</Link></div></div>
      </header>
      <main key={activeModule} className="page-enter p-4 sm:p-7 xl:p-9">
        {unavailable && <p role="alert" className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-200">PostgreSQL is temporarily unavailable. Operational controls remain protected while data reconnects.</p>}
        {activeModule === "overview" && <Overview context={context} env={env}/>}
        {activeModule === "ai" && <AiOperations context={context} model={env.OPENAI_DIAGNOSIS_MODEL}/>}
        {activeModule === "bookings" && <BookingOperations rows={bookingRows(bookings)} technicianEmail={env.TECHNICIAN_EMAIL}/>}
        {activeModule === "customers" && <Customers bookings={bookings} diagnoses={diagnoses}/>}
        {activeModule === "technicians" && <Technicians bookings={bookings} technicianEmail={env.TECHNICIAN_EMAIL}/>}
        {activeModule === "reports" && <Reports diagnoses={diagnoses}/>}
        {activeModule === "inventory" && <Inventory diagnoses={diagnoses}/>}
        {activeModule === "prompt" && <Prompt model={env.OPENAI_DIAGNOSIS_MODEL}/>}
        {activeModule === "logs" && <AuditLogs bookings={bookings} diagnoses={diagnoses}/>}
        {activeModule === "notifications" && <Notifications bookings={bookings}/>}
        {activeModule === "settings" && <SettingsPanel env={env}/>}
        {activeModule === "profile" && <Profile email={session.email}/>}
      </main>
    </div>
  </div>;
}

function Overview({ context, env }: { context: ReturnType<typeof buildContext>; env: ReturnType<typeof getServerEnv> }) {
  const metrics = [
    [Users, "Total users", String(context.customers.size + context.technicians.size + 1)], [UserCog, "Customers", String(context.customers.size)], [Wrench, "Technicians", String(context.technicians.size || 1)],
    [BrainCircuit, "AI diagnoses today", String(context.today.length)], [BarChart3, "AI diagnoses this month", String(context.month.length)], [ClipboardList, "Pending repairs", String(context.pending.length)],
    [Activity, "Active repairs", String(context.active.length)], [CheckCircle2, "Completed repairs", String(context.completed.length)], [Gauge, "Average AI confidence", `${context.averageConfidence}%`],
    [CircleDollarSign, "Revenue estimate", money(context.revenue)], [FileText, "Open tickets", String(context.active.length)], [HeartPulse, "Platform health", context.unavailable ? "Degraded" : "Operational"],
  ] as const;
  const activity = recentActivity(context.bookings, context.diagnoses).slice(0, 6);
  return <section>
    <div className="relative overflow-hidden rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_10%_10%,#2563eb55,transparent_35%),radial-gradient(circle_at_90%_90%,#06b6d42d,transparent_32%)]"/><div className="relative flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="eyebrow !text-cyan-300">Executive overview</p><h1 className="h1 my-2 font-bold">Good {greeting()}, Administrator</h1><p className="m-0 max-w-2xl text-slate-300">Monitor AI diagnosis intelligence, repair operations, technician workloads, and customer outcomes from one trusted workspace.</p><div className="mt-5 flex flex-wrap gap-2"><span className="badge bg-green-400/15 text-green-300"><HeartPulse size={14}/>All systems monitored</span><span className="badge bg-white/10 text-slate-200"><Cpu size={14}/>{env.OPENAI_DIAGNOSIS_MODEL}</span></div></div><div className="grid grid-cols-2 gap-3 text-xs"><HeroHealth label="OpenAI" value={env.OPENAI_API_KEY ? "Connected" : "Fallback"} ready={Boolean(env.OPENAI_API_KEY)}/><HeroHealth label="Authentication" value="Secure" ready={Boolean(env.AUTH_SECRET)}/></div></div></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">{metrics.map(([Icon, label, value]) => <Metric key={label} icon={<Icon size={19}/>} label={label} value={value}/>)}</div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.4fr_.8fr]">
      <div className="card"><SectionHead eyebrow="Recent activity" title="Platform activity" copy="Latest persisted diagnosis and repair events."/><div className="grid gap-1">{activity.map((event, index) => <div className="flex gap-3 border-b py-3 last:border-0" key={`${event.at.toISOString()}-${index}`}><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-blue-500"/><span className="flex-1"><b className="block text-sm">{event.action}</b><small className="text-slate-500">{event.detail}</small></span><time className="text-xs text-slate-500">{event.at.toLocaleDateString()}</time></div>)}{!activity.length && <Empty copy="Activity appears after diagnoses and bookings begin."/>}</div></div>
      <div className="grid gap-6"><div className="card"><SectionHead eyebrow="AI summary" title="Repair intelligence" copy="A concise view of current AI activity."/><div className="grid grid-cols-2 gap-3"><MiniStat label="Reports" value={String(context.diagnoses.length)}/><MiniStat label="Confidence" value={`${context.averageConfidence}%`}/><MiniStat label="With images" value={String(context.diagnoses.filter(item => item.imageCount > 0).length)}/><MiniStat label="Model" value="GPT-5.6"/></div></div><div className="card"><SectionHead eyebrow="Quick actions" title="Open a workspace" copy="Go directly to the next operational task."/><div className="grid gap-2"><Link className="btn btn-primary justify-start" href="/admin?module=bookings">Review bookings</Link><Link className="btn btn-secondary justify-start" href="/admin?module=reports">Inspect AI reports</Link><Link className="btn btn-secondary justify-start" href="/admin?module=settings">Check platform health</Link></div></div></div>
    </div>
  </section>;
}

function AiOperations({ context, model }: { context: ReturnType<typeof buildContext>; model: string }) {
  const brands = countBy(context.diagnoses.map(item => item.brand));
  const faults = countBy(context.diagnoses.map(item => item.problemCategory));
  const daily = lastSevenDays(context.diagnoses);
  return <section><SectionHead eyebrow="AI operations" title="GPT-5.6 usage intelligence" copy="Responses API activity, structured-output quality, device patterns, and explicit observability gaps."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card icon={<Smartphone/>} label="Most diagnosed device" value={brands[0]?.label || "No reports yet"}/><Card icon={<BrainCircuit/>} label="Most common fault" value={faults[0]?.label || "No reports yet"}/><Card icon={<Gauge/>} label="Average confidence" value={`${context.averageConfidence}%`}/><Card icon={<CircleDollarSign/>} label="Average cost estimate" value={averageDiagnosisCost(context.diagnoses)}/><Card icon={<Activity/>} label="Daily AI activity" value={String(context.today.length)}/><Card icon={<BarChart3/>} label="Weekly AI activity" value={String(daily.reduce((sum, point) => sum + point.value, 0))}/><Card icon={<FileText/>} label="Monthly AI activity" value={String(context.month.length)}/><Card icon={<Cpu/>} label="Model and API" value={`${model} · Responses API`}/></div><div className="mt-6"><OperationsCharts daily={daily} brands={brands} faults={faults} statuses={countBy(context.bookings.map(item => item.status))} activity={activityHeatmap(context.diagnoses)}/></div><p className="mt-4 text-xs text-slate-500">Token usage and latency are marked unavailable until persistent OpenAI telemetry is instrumented; no values are fabricated.</p></section>;
}

function Customers({ bookings, diagnoses }: { bookings: Bookings; diagnoses: Diagnoses }) {
  const emails = new Set([...bookings.map(item => item.customerEmail), ...diagnoses.map(item => item.customerEmail).filter(Boolean) as string[]]);
  const customers = Array.from(emails).map(email => { const repairs = bookings.filter(item => item.customerEmail === email); return { email, bookings: repairs.length, completed: repairs.filter(item => item.status === "Completed").length, invoices: repairs.filter(item => item.status === "Completed").length, diagnoses: diagnoses.filter(item => item.customerEmail === email).length, devices: new Set([...repairs.map(item => `${item.brand} ${item.deviceModel}`), ...diagnoses.filter(item => item.customerEmail === email).map(item => `${item.brand} ${item.deviceModel}`)]).size }; });
  return <section className="card overflow-x-auto"><SectionHead eyebrow="Customer intelligence" title="Customer management" copy="Profiles, diagnosis history, repairs, and invoice readiness aggregated from persisted activity."/><table className="w-full min-w-[820px] text-left text-sm"><thead><tr>{["Customer profile", "Devices", "AI history", "Repairs", "Completed", "Invoices", "Account"].map(label => <th className="border-b py-3 text-xs uppercase tracking-wide text-slate-500" key={label}>{label}</th>)}</tr></thead><tbody>{customers.map(customer => <tr key={customer.email}><td className="border-b py-4 font-semibold">{customer.email}</td><td className="border-b">{customer.devices}</td><td className="border-b">{customer.diagnoses}</td><td className="border-b">{customer.bookings}</td><td className="border-b">{customer.completed}</td><td className="border-b">{customer.invoices}</td><td className="border-b"><span className="badge badge-green">Active</span></td></tr>)}</tbody></table>{!customers.length && <Empty copy="Customer activity appears after the first diagnosis or booking."/>}</section>;
}

function Technicians({ bookings, technicianEmail }: { bookings: Bookings; technicianEmail: string }) {
  const active = bookings.filter(item => item.assignedTechnicianEmail === technicianEmail && item.status !== "Completed").length;
  return <section><SectionHead eyebrow="Repair workforce" title="Technician performance" copy="Assignments, availability, and completed work for the configured technician workspace."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card icon={<UserCog/>} label="Approved technician" value={technicianEmail}/><Card icon={<Wrench/>} label="Current assignments" value={`${active} active repairs`}/><Card icon={<Activity/>} label="Availability" value={active < 5 ? "Available" : "At capacity"}/><Card icon={<CheckCircle2/>} label="Completed repairs" value={String(bookings.filter(item => item.assignedTechnicianEmail === technicianEmail && item.status === "Completed").length)}/><Card icon={<Gauge/>} label="Customer rating" value="Not collected yet"/></div><p className="mt-4 text-xs text-slate-500">Ratings remain unscored until a verified customer-review workflow is available.</p></section>;
}

function Reports({ diagnoses }: { diagnoses: Diagnoses }) {
  const rows: ReportOperation[] = diagnoses.slice(0, 100).map(report => ({ id: report.id, device: `${report.brand} ${report.deviceModel}`, category: report.problemCategory, confidence: confidenceOf(report.result) ?? 0, images: report.imageCount, generated: report.createdAt.toLocaleString(), result: JSON.stringify(report.result, null, 2) }));
  return <ReportOperations rows={rows}/>;
}

function Inventory({ diagnoses }: { diagnoses: Diagnoses }) { const parts = topParts(diagnoses); return <section><SectionHead eyebrow="Parts intelligence" title="Inventory signals" copy="Recommended parts extracted from structured AI reports indicate likely future demand."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{parts.map(item => <Card key={item.label} icon={<PackageSearch/>} label={item.label} value={`${item.value} recommendations`}/>)}{!parts.length && <div className="card sm:col-span-2"><Empty copy="Parts demand appears as AI reports recommend replacements."/></div>}</div></section>; }

function Prompt({ model }: { model: string }) {
  return <section><SectionHead eyebrow="Model governance" title="AI Configuration Center" copy="Read-only production status with deployment-managed prompt governance."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card icon={<Cpu/>} label="Current model" value={model}/><Card icon={<BrainCircuit/>} label="API" value="Responses API"/><Card icon={<Smartphone/>} label="Vision" value="Enabled · up to 5 images"/><Card icon={<CheckCircle2/>} label="Structured outputs" value="Enabled · Zod validated"/><Card icon={<FileText/>} label="Prompt version" value="v1 · Repair diagnosis"/><Card icon={<Gauge/>} label="Temperature" value="Model managed"/><Card icon={<ShieldCheck/>} label="Confidence threshold" value="Schema constrained"/><Card icon={<HeartPulse/>} label="Status" value="Read only · deployment controlled"/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_.8fr]"><div className="card bg-slate-950 text-slate-200"><div className="flex items-center justify-between"><h2 className="m-0 text-base font-semibold">System prompt preview</h2><span className="badge bg-white/10 text-cyan-300">v1 active</span></div><pre className="mt-5 max-h-72 overflow-auto whitespace-pre-wrap rounded-xl border border-slate-800 bg-black/20 p-4 text-xs leading-6 text-slate-400">You are FixMind AI, a cautious senior electronic repair diagnostician. Analyze supplied symptoms and images. Return validated structured output with likely faults, confidence, cost, duration, required tools and parts, safety warnings, and the safest recommended next action.</pre><p className="mb-0 text-xs text-slate-500">Secrets and API keys are never exposed here.</p></div><div className="grid gap-6"><div className="card"><h2 className="mt-0 text-base font-semibold">Prompt history</h2><div className="rounded-xl border p-3"><div className="flex justify-between gap-3"><b className="text-sm">v1 · Active</b><span className="badge badge-green">Production</span></div><p className="mb-0 text-xs text-slate-500">Structured diagnosis with safety guidance, cost, duration, tools, and parts.</p></div><p className="mb-0 text-xs text-slate-500">Additional history appears after versioned prompt deployments.</p></div><div className="card"><h2 className="mt-0 text-base font-semibold">Validation controls</h2><div className="grid gap-2"><Link href="/diagnose" className="btn btn-primary">Test prompt safely</Link><button disabled title="Rollback requires a prior prompt version" className="btn btn-secondary">Rollback unavailable</button></div></div></div></div></section>;
}

function AuditLogs({ bookings, diagnoses }: { bookings: Bookings; diagnoses: Diagnoses }) {
  const rows: AuditOperation[] = recentActivity(bookings, diagnoses).slice(0, 100).map((event, index) => ({ id: `${event.at.toISOString()}-${index}`, time: event.at.toLocaleString(), action: event.action, detail: event.detail, category: event.action.includes("Diagnosis") ? "AI" : event.action.includes("Booking") ? "Booking" : "Repair" }));
  return <AuditOperations rows={rows}/>;
}

function Notifications({ bookings }: { bookings: Bookings }) { const pending = bookings.filter(item => ["Booked", "Approved", "Received"].includes(item.status)); const unassigned = bookings.filter(item => item.status !== "Completed" && !item.assignedTechnicianEmail); return <section><SectionHead eyebrow="Attention center" title="Operational notifications" copy="The most important platform conditions requiring administrator attention."/><div className="grid gap-3">{pending.length > 0 && <Notice tone="amber" title={`${pending.length} repairs need review`} copy="Approve, assign, or update pending bookings from the operations queue."/>}{unassigned.length > 0 && <Notice tone="blue" title={`${unassigned.length} active repairs are unassigned`} copy="Assign a technician so work appears in the technician workspace."/>}<Notice tone="green" title="AI reliability controls enabled" copy="Structured validation, retries, cache, rate limits, and fallback are active."/></div></section>; }

function SettingsPanel({ env }: { env: ReturnType<typeof getServerEnv> }) { return <section><SectionHead eyebrow="Environment readiness" title="Platform health" copy="Live configuration and service readiness without exposing sensitive values."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Health label="OpenAI API" ready={Boolean(env.OPENAI_API_KEY)} detail={env.OPENAI_API_KEY ? "Connected server-side" : "Demo fallback active"}/><Health label="PostgreSQL" ready={Boolean(env.DATABASE_URL)} detail="Configured"/><Health label="Authentication" ready={Boolean(env.AUTH_SECRET)} detail="Signed sessions enabled"/><Health label="Image processing" ready detail="Browser compression enabled"/><Health label="Storage" ready={Boolean(env.DATABASE_URL)} detail="PostgreSQL persistence"/><Health label="Repair queue" ready={Boolean(env.DATABASE_URL)} detail="Database-backed operations"/><Health label="Email service" ready={false} detail="Not configured"/><Health label="Notifications" ready detail="In-app operational alerts"/></div></section>; }

function Profile({ email }: { email: string }) { return <section className="card"><SectionHead eyebrow="Administrator identity" title="Profile and security" copy="Current signed administrator session and role status."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card icon={<UserCog/>} label="Administrator" value={email}/><Card icon={<ShieldCheck/>} label="Role" value="Verified administrator"/><Card icon={<Activity/>} label="Inactivity timeout" value="3 minutes"/><Card icon={<HeartPulse/>} label="Security status" value="Signed · HTTP-only · SameSite"/></div></section>; }

function buildContext(bookings: Bookings, diagnoses: Diagnoses) {
  const now = new Date(); const todayAt = new Date(now.getFullYear(), now.getMonth(), now.getDate()); const monthAt = new Date(now.getFullYear(), now.getMonth(), 1);
  const confidence = diagnoses.map(item => confidenceOf(item.result)).filter((value): value is number => value !== null);
  return { bookings, diagnoses, unavailable: false, active: bookings.filter(item => !["Completed", "Rejected"].includes(item.status)), pending: bookings.filter(item => ["Booked", "Approved", "Received"].includes(item.status)), completed: bookings.filter(item => item.status === "Completed"), today: diagnoses.filter(item => item.createdAt >= todayAt), month: diagnoses.filter(item => item.createdAt >= monthAt), averageConfidence: confidence.length ? Math.round(confidence.reduce((sum, value) => sum + value, 0) / confidence.length) : 0, customers: new Set([...bookings.map(item => item.customerEmail), ...diagnoses.map(item => item.customerEmail).filter(Boolean)]), technicians: new Set(bookings.map(item => item.assignedTechnicianEmail).filter(Boolean)), revenue: bookings.reduce((sum, item) => sum + item.estimatedTotalCents, 0) };
}

function bookingRows(bookings: Bookings): BookingOperation[] { return bookings.map(item => ({ id: item.id, device: `${item.brand} ${item.deviceModel}`, service: item.service, customer: item.customerName, email: item.customerEmail, appointment: item.appointmentAt.toLocaleString(), status: item.status, technician: item.assignedTechnicianEmail || "", total: money(item.estimatedTotalCents) })); }
function recentActivity(bookings: Bookings, diagnoses: Diagnoses) { return [...bookings.slice(0, 12).map(item => ({ at: item.updatedAt, action: item.assignedTechnicianEmail ? `Repair ${item.status.toLowerCase()}` : "Booking created", detail: `${item.brand} ${item.deviceModel} · ${item.customerEmail}` })), ...diagnoses.slice(0, 12).map(item => ({ at: item.createdAt, action: "Diagnosis completed", detail: `${item.brand} ${item.deviceModel} · ${item.problemCategory}` }))].sort((a, b) => b.at.getTime() - a.at.getTime()); }
function confidenceOf(value: unknown) { if (value && typeof value === "object" && !Array.isArray(value) && "confidence" in value) { const confidence = (value as { confidence?: unknown }).confidence; return typeof confidence === "number" ? confidence : null; } return null; }
function countBy(values: string[]): ChartPoint[] { const counts = new Map<string, number>(); values.forEach(value => counts.set(value, (counts.get(value) || 0) + 1)); return Array.from(counts, ([label, value]) => ({ label, value })).sort((a, b) => b.value - a.value); }
function lastSevenDays(diagnoses: Diagnoses): ChartPoint[] { return Array.from({ length: 7 }, (_, offset) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - offset)); const next = new Date(date); next.setDate(next.getDate() + 1); return { label: date.toLocaleDateString("en-US", { weekday: "short" }), value: diagnoses.filter(item => item.createdAt >= date && item.createdAt < next).length }; }); }
function activityHeatmap(diagnoses: Diagnoses): HeatPoint[] { const periods = ["00–04", "04–08", "08–12", "12–16", "16–20", "20–24"]; return Array.from({ length: 7 }, (_, offset) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - offset)); const next = new Date(date); next.setDate(next.getDate() + 1); const day = date.toLocaleDateString("en-US", { weekday: "short" }); return periods.map((period, index) => ({ day, period, value: diagnoses.filter(item => item.createdAt >= date && item.createdAt < next && Math.floor(item.createdAt.getHours() / 4) === index).length })); }).flat(); }
function topParts(diagnoses: Diagnoses): ChartPoint[] { const parts: string[] = []; diagnoses.forEach(item => { const value = item.result; if (value && typeof value === "object" && !Array.isArray(value) && "requiredParts" in value) { const list = (value as { requiredParts?: unknown }).requiredParts; if (Array.isArray(list)) parts.push(...list.filter((part): part is string => typeof part === "string")); } }); return countBy(parts).slice(0, 8); }
function averageDiagnosisCost(diagnoses: Diagnoses) { const values: number[] = []; diagnoses.forEach(item => { const result = item.result; if (result && typeof result === "object" && !Array.isArray(result) && "estimatedCost" in result) { const cost = (result as { estimatedCost?: unknown }).estimatedCost; if (cost && typeof cost === "object" && !Array.isArray(cost)) { const minimum = (cost as { minimum?: unknown }).minimum; const maximum = (cost as { maximum?: unknown }).maximum; if (typeof minimum === "number" && typeof maximum === "number") values.push((minimum + maximum) / 2); } } }); return values.length ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(values.reduce((sum, value) => sum + value, 0) / values.length) : "No cost data"; }
function moduleTitle(module: AdminModule) { return ({ overview: "Executive overview", analytics: "Platform analytics", ai: "AI operations", bookings: "Booking management", customers: "Customer management", technicians: "Technician performance", reports: "AI reports", inventory: "Inventory signals", prompt: "Model governance", logs: "Audit activity", notifications: "Attention center", settings: "System settings", profile: "Administrator profile" } as const)[module]; }
function greeting() { const hour = new Date().getHours(); return hour < 12 ? "morning" : hour < 18 ? "afternoon" : "evening"; }
function money(cents: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(cents / 100); }
function HeroHealth({ label, value, ready }: { label: string; value: string; ready: boolean }) { return <div className="rounded-xl border border-white/10 bg-white/5 p-3"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${ready ? "bg-green-400" : "bg-amber-400"}`}/><span className="text-slate-400">{label}</span></div><b className="mt-1 block">{value}</b></div>; }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <article className="card group !p-5 hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-lg"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600">{icon}</span><p className="mt-5 mb-1 text-xs text-slate-500">{label}</p><p className="m-0 text-2xl font-bold tracking-tight">{value}</p></article>; }
function SectionHead({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="mb-5"><p className="eyebrow mb-1">{eyebrow}</p><h1 className="m-0 text-2xl font-semibold">{title}</h1><p className="mt-1 mb-0 text-sm leading-6 text-slate-500">{copy}</p></div>; }
function Card({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="card"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600">{icon}</span><p className="mt-5 mb-1 text-xs text-slate-500">{label}</p><b className="break-words text-lg">{value}</b></div>; }
function MiniStat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-900"><small className="text-slate-500">{label}</small><b className="mt-1 block text-sm">{value}</b></div>; }
function Empty({ copy }: { copy: string }) { return <p className="m-0 py-8 text-center text-sm text-slate-500">{copy}</p>; }
function Notice({ tone, title, copy }: { tone: "amber" | "blue" | "green"; title: string; copy: string }) { const colors = tone === "amber" ? "border-amber-200 bg-amber-50 text-amber-900" : tone === "green" ? "border-green-200 bg-green-50 text-green-900" : "border-blue-200 bg-blue-50 text-blue-900"; return <div className={`rounded-2xl border p-4 ${colors}`}><b className="block text-sm">{title}</b><p className="mt-1 mb-0 text-sm opacity-80">{copy}</p></div>; }
function Health({ label, ready, detail }: { label: string; ready: boolean; detail: string }) { return <div className="card"><div className="flex items-center justify-between"><span className={`grid h-10 w-10 place-items-center rounded-xl ${ready ? "bg-green-50 text-green-600" : "bg-amber-50 text-amber-600"}`}><ShieldCheck size={19}/></span><span className={`h-2.5 w-2.5 rounded-full ${ready ? "bg-green-500" : "bg-amber-500"}`}/></div><p className="mt-5 mb-1 text-sm font-semibold">{label}</p><p className="m-0 text-xs text-slate-500">{detail}</p></div>; }
