import Link from "next/link";
import { TopNav, PageTitle, StatCard } from "@/components/ui";
import { ArrowRight, BrainCircuit, DollarSign, Plus, Search, Smartphone, User, Wrench } from "lucide-react";
import { requireSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function Dashboard(){
  const session=await requireSession("customer");
  let bookings:Awaited<ReturnType<typeof prisma.booking.findMany>>=[];
  let diagnoses:Awaited<ReturnType<typeof prisma.diagnosis.findMany>>=[];
  let unavailable=false;
  try{[bookings,diagnoses]=await Promise.all([prisma.booking.findMany({where:{customerEmail:session.email},orderBy:{createdAt:"desc"}}),prisma.diagnosis.findMany({where:{customerEmail:session.email},orderBy:{createdAt:"desc"},take:10})])}catch{unavailable=true}
  const active=bookings.filter(x=>x.status!=="Completed");
  const completed=bookings.filter(x=>x.status==="Completed");
  const spent=completed.reduce((sum,x)=>sum+x.estimatedTotalCents,0);
  const devices=Array.from(new Set([...bookings.map(x=>`${x.brand} ${x.deviceModel}`),...diagnoses.map(x=>`${x.brand} ${x.deviceModel}`)]));
  return <div className="app-shell"><TopNav/><main className="container py-10">
    <PageTitle eyebrow="Customer portal" title="Your FixMind dashboard" copy="Diagnoses, bookings, devices, invoices, and repair progress in one place."/>
    <div className="grid-4"><StatCard icon={<Wrench/>} title="Active repairs" value={String(active.length)}/><StatCard icon={<BrainCircuit/>} title="AI diagnoses" value={String(diagnoses.length)}/><StatCard icon={<Smartphone/>} title="Devices" value={String(devices.length)}/><StatCard icon={<DollarSign/>} title="Total spent" value={money(spent)}/></div>
    {unavailable&&<p role="alert" className="mt-6 rounded-xl bg-amber-50 p-4 text-amber-900">Your saved history is temporarily unavailable. AI diagnosis and booking remain accessible.</p>}
    <div className="mt-6 grid gap-6 lg:grid-cols-[2fr_1fr]"><section className="card"><div className="mb-5 flex justify-between"><h2 className="m-0 text-xl font-semibold">Upcoming repairs</h2><span className="muted text-sm">{active.length} active</span></div>{active.length?active.slice(0,3).map(x=><Link key={x.id} href={`/dashboard/repairs/${x.id}`} className="mb-3 flex items-center gap-4 rounded-2xl border p-4 text-inherit no-underline"><Smartphone className="text-blue-600"/><span className="flex-1"><b>{x.brand} {x.deviceModel} · {x.service}</b><small className="muted block">{x.location} · {x.appointmentAt.toLocaleString()}</small></span><span className="badge badge-blue">{x.status}</span><ArrowRight size={17}/></Link>):<Empty title="No active repairs" copy="Book a repair when you are ready for professional help." href="/book" action="Book a repair"/>}</section><aside className="card"><h2 className="mt-0 text-xl font-semibold">Quick actions</h2><div className="grid gap-3"><Link href="/diagnose" className="btn btn-primary justify-start"><Search size={18}/>New AI diagnosis</Link><Link href="/book" className="btn btn-secondary justify-start"><Plus size={18}/>Book a repair</Link><Link href="/resources" className="btn btn-secondary justify-start"><Smartphone size={18}/>Device care guides</Link></div></aside></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="card"><div className="mb-5 flex items-center justify-between"><h2 className="m-0 text-xl font-semibold">AI diagnosis history</h2><BrainCircuit className="text-blue-600"/></div>{diagnoses.length?<div className="grid gap-3">{diagnoses.map(x=><div key={x.id} className="flex items-center gap-4 rounded-xl border p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><BrainCircuit size={18}/></span><span className="flex-1"><b className="block">{x.brand} {x.deviceModel}</b><small className="muted">{x.problemCategory} · {x.createdAt.toLocaleDateString()}</small></span><span className="font-mono text-xs text-slate-400">{x.id.slice(-6).toUpperCase()}</span></div>)}</div>:<Empty title="No saved diagnoses" copy="Your completed AI assessments will appear here." href="/diagnose" action="Start diagnosis"/>}</section><section className="card"><h2 className="mt-0 text-xl font-semibold">Devices & profile</h2><div className="mb-5 flex items-center gap-3 rounded-xl bg-slate-50 p-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-slate-900 text-white"><User size={18}/></span><span><b className="block">Customer account</b><small className="muted">{session.email}</small></span></div><div className="flex flex-wrap gap-2">{devices.length?devices.map(device=><span key={device} className="badge badge-blue">{device}</span>):<p className="muted text-sm">Devices are added automatically from diagnoses and bookings.</p>}</div></section></div>
    <section className="card mt-6 overflow-x-auto"><h2 className="mt-0 text-xl font-semibold">Invoices & repair history</h2><table className="w-full min-w-[680px] text-left text-sm"><thead><tr>{["Repair","Invoice","Date","Status","Total"].map(x=><th className="border-b py-3" key={x}>{x}</th>)}</tr></thead><tbody>{bookings.map(x=><tr key={x.id}><td className="border-b py-4 font-semibold">{x.brand} {x.deviceModel} · {x.service}</td><td className="border-b">{x.status==="Completed"?`INV-${x.id.slice(-6).toUpperCase()}`:"Pending"}</td><td className="border-b">{x.createdAt.toLocaleDateString()}</td><td className="border-b"><span className="badge badge-blue">{x.status}</span></td><td className="border-b">{money(x.estimatedTotalCents)}</td></tr>)}</tbody></table>{!bookings.length&&!unavailable&&<p className="muted py-8 text-center">Invoices appear after a repair booking is completed.</p>}</section>
  </main></div>
}
function Empty({title,copy,href,action}:{title:string;copy:string;href:string;action:string}){return <div className="rounded-2xl border border-dashed p-7 text-center"><p className="font-semibold">{title}</p><p className="muted text-sm">{copy}</p><Link href={href} className="btn btn-primary">{action}</Link></div>}
function money(cents:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100)}
